spring:
  r2dbc:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    pool:
      initial-size: 5
      max-size: 20
      max-idle-time: 30m

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}
  # sql:
  #   init:
  #     mode: always





